---
- name: Make sure web root exists
  file:
    path: "{{ certbot_root }}"
    state: directory
    owner: "{{ certbot_www_user }}"
    group: "{{ certbot_www_group }}"
    mode: 0755

- name: Generate certificate
  shell: "certbot certonly --non-interactive --agree-tos --email {{ certbot_email }} --webroot -w {{ certbot_root }} -d {{ certbot_domain }}"
  when: certbot_ci_build == false

- name: Prepare certs dirs
  file:
    path: "/etc/letsencrypt/{{ item }}"
    owner: "{{ certbot_www_user }}"
    group: "{{ certbot_www_group }}"
    state: directory
    mode: g+rx
  with_items:
    - archive
    - live

- name: Check if old certs exist
  stat:
    path: "/etc/ssl/{{ certbot_domain }}.pem"
  register: certbot_old_cert
  changed_when: false

- name: Remove old certs
  file:
    path: "/etc/ssl/{{ certbot_domain }}.{{ item }}"
    state: absent
  with_items:
    - 'pem'
    - 'key'
  when: certbot_link|bool == true and (certbot_old_cert.stat.exists and certbot_old_cert.stat.islnk == False)

- name: Make sure cert directory exists
  file:
    path: "/etc/letsencrypt/live/{{ certbot_domain }}"
    state: directory
  when: certbot_ci_build == true

- name: Make sure cert files exist
  file:
    path: "/etc/letsencrypt/live/{{ certbot_domain }}/{{ item.src }}"
    state: touch
  with_items:
    - { src: 'fullchain.pem' }
    - { src: 'privkey.pem' }
  when: certbot_ci_build == true
  changed_when: false

- name: Link certs
  file:
    src: "/etc/letsencrypt/live/{{ certbot_domain }}/{{ item.src }}"
    dest: "/etc/ssl/{{ certbot_domain }}.{{ item.dest }}"
    state: link
  with_items:
    - { src: 'fullchain.pem', dest: 'pem' }
    - { src: 'privkey.pem', dest: 'key' }
  when: certbot_link|bool == true

- name: Configure web directory permissions
  file:
    path: "{{ certbot_root }}"
    state: directory
    owner: www-data
    group: www-data
    recurse: true

- name: Install cron
  cron:
    name: regenerate ssl cert
    hour: "{{ certbot_regenerate_hour }}"
    minute: "{{ certbot_regenerate_minute }}"
    day: "{{ certbot_regenerate_day_of_month }}"
    job: "certbot certonly --non-interactive --agree-tos --email {{ certbot_email }} --webroot -w {{ certbot_root }} -d {{ certbot_domain }}"
  when: certbot_set_cron|bool == true
